SET search_path TO "pi_scoring";
-- Idempotence : on vide le schéma métier avant re-seed
TRUNCATE "RolePermission","Permission","ScoringOption","ScoringRange","ScoringCriterion","RedFlagRule","ScoringDomain","ScoringModelVersion","ScoringModel","ProvisionRate","RegulatoryTrigger","GuaranteeType","RegulatoryClass","RegulatoryRegime","Guarantee","ProjectInput","RealEstateProject","Promoter","ClassificationRun","ProvisionRun","ScoringRun","CriterionResult","DomainResult","WorkflowStep","Comment","Attachment","AuditLog","ImportBatch","User","Role" RESTART IDENTITY CASCADE;
INSERT INTO "Permission"("id","code","label") VALUES ('perm_project.read','project.read','Consulter les projets');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_project.write','project.write','Modifier les projets');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_scoring.run','scoring.run','Lancer un scoring');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_scoring.validate','scoring.validate','Valider un scoring');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_model.read','model.read','Consulter le modèle');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_model.write','model.write','Administrer le modèle');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_regime.read','regime.read','Consulter les régimes');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_regime.write','regime.write','Administrer les régimes');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_import.run','import.run','Importer des données');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_export.run','export.run','Exporter des rapports');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_audit.read','audit.read','Consulter l''audit');
INSERT INTO "Permission"("id","code","label") VALUES ('perm_admin.users','admin.users','Gérer les utilisateurs');
INSERT INTO "Role"("id","name","label") VALUES ('role_ADMIN','ADMIN'::"RoleName",'Administrateur');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_project.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_project.write');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_scoring.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_scoring.validate');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_model.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_model.write');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_regime.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_regime.write');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_import.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_export.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_audit.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_ADMIN','perm_admin.users');
INSERT INTO "Role"("id","name","label") VALUES ('role_RISK_ANALYST','RISK_ANALYST'::"RoleName",'Analyste Risque');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_project.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_project.write');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_scoring.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_model.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_regime.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_import.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_export.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RISK_ANALYST','perm_audit.read');
INSERT INTO "Role"("id","name","label") VALUES ('role_RELATIONSHIP_MANAGER','RELATIONSHIP_MANAGER'::"RoleName",'Chargé d''affaires');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RELATIONSHIP_MANAGER','perm_project.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RELATIONSHIP_MANAGER','perm_project.write');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RELATIONSHIP_MANAGER','perm_scoring.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_RELATIONSHIP_MANAGER','perm_export.run');
INSERT INTO "Role"("id","name","label") VALUES ('role_MANAGER','MANAGER'::"RoleName",'Manager / Comité');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_project.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_scoring.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_scoring.validate');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_model.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_regime.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_export.run');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_MANAGER','perm_audit.read');
INSERT INTO "Role"("id","name","label") VALUES ('role_AUDITOR','AUDITOR'::"RoleName",'Auditeur');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_AUDITOR','perm_project.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_AUDITOR','perm_model.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_AUDITOR','perm_regime.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_AUDITOR','perm_audit.read');
INSERT INTO "RolePermission"("roleId","permissionId") VALUES ('role_AUDITOR','perm_export.run');
INSERT INTO "User"("id","email","name","roleId","updatedAt") VALUES ('user_ADMIN','admin@bank.ma','Amine Admin','role_ADMIN',now());
INSERT INTO "User"("id","email","name","roleId","updatedAt") VALUES ('user_RISK_ANALYST','analyst@bank.ma','Rita Analyste','role_RISK_ANALYST',now());
INSERT INTO "User"("id","email","name","roleId","updatedAt") VALUES ('user_RELATIONSHIP_MANAGER','rm@bank.ma','Karim Chargé d''affaires','role_RELATIONSHIP_MANAGER',now());
INSERT INTO "User"("id","email","name","roleId","updatedAt") VALUES ('user_MANAGER','manager@bank.ma','Salma Manager','role_MANAGER',now());
INSERT INTO "User"("id","email","name","roleId","updatedAt") VALUES ('user_AUDITOR','auditor@bank.ma','Omar Auditeur','role_AUDITOR',now());
INSERT INTO "ScoringModel"("id","code","name","description") VALUES ('model_PI','PI_PROMOTION','Scoring Promotion Immobilière','Modèle D1..D5 (V1.0)');
INSERT INTO "ScoringModelVersion"("id","modelId","version","status","scoreScale","bamCoefficients","decisionThresholds","segmentAdjustments","zoneAdjustments","publishedAt") VALUES ('ver_1','model_PI','v1.0.0','PUBLISHED',5,'{"SAIN":1,"SENSIBLE":0.9,"PRE_DOUTEUX":0.7,"DOUTEUX":0.4,"COMPROMIS":0.2,"CTX":0}'::jsonb,'{"go":75,"goWithConditions":65,"watchList":50}'::jsonb,'{"social":0,"intermediaire":-0.05,"moyen_haut":0,"touristique":-0.07,"bureaux":-0.05,"commerces":-0.03,"villas":-0.04}'::jsonb,'{"casa_centre":0,"casa_peripherie":-0.05,"rabat_centre":0.02,"rabat_peripherie":0,"tanger":0,"marrakech":-0.07,"agadir":0,"fes_oriental":-0.03,"regions_interieures":-0.05}'::jsonb,now());
INSERT INTO "ScoringDomain"("id","versionId","code","name","weight","orderIndex") VALUES ('dom_D1','ver_1','D1','Sponsor & Gouvernance',0.22,0);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D1C1','dom_D1','D1C1','Projets similaires livrés (5 ans)','NUM'::"CriterionType",0.2,'promoter_completed_projects',false,NULL,0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C1_0','crit_D1C1',NULL,1,0,'Aucun (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C1_1','crit_D1C1',1,3,3,'1-2 (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C1_2','crit_D1C1',3,NULL,5,'≥3 (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D1C2','dom_D1','D1C2','Gearing promoteur (dettes nettes / FP)','NUM'::"CriterionType",0.25,'promoter_gearing',false,NULL,1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C2_0','crit_D1C2',NULL,100,5,'≤100% (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C2_1','crit_D1C2',100,150,3,'100-150% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C2_2','crit_D1C2',150,NULL,0,'>150% (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D1C3','dom_D1','D1C3','Gouvernance & structure juridique','QUAL'::"CriterionType",0.15,'governance_quality',false,NULL,2);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D1C3_opaque','crit_D1C3','opaque','Opaque',0,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D1C3_partielle','crit_D1C3','partielle','Partielle',3,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D1C3_claire','crit_D1C3','claire','Claire / structurée',5,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D1C4','dom_D1','D1C4','Concentration mono-projet (CA projet / CA total)','NUM'::"CriterionType",0.15,'mono_project_concentration',false,NULL,3);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C4_0','crit_D1C4',NULL,40,5,'≤40% (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C4_1','crit_D1C4',40,60,3,'40-60% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C4_2','crit_D1C4',60,NULL,0,'>60% (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D1C5','dom_D1','D1C5','Typologie promoteur','QUAL'::"CriterionType",0.1,'promoter_type',false,NULL,4);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D1C5_opportuniste','crit_D1C5','opportuniste','Opportuniste',1,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D1C5_regional','crit_D1C5','regional','Régional',3,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D1C5_structure','crit_D1C5','structure','Structuré',5,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D1C6','dom_D1','D1C6','Apport effectif (injecté / prévu)','NUM'::"CriterionType",0.15,'equity_injected_ratio',true,0,5);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C6_0','crit_D1C6',NULL,80,0,'<80% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C6_1','crit_D1C6',80,100,3,'80-100% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D1C6_2','crit_D1C6',100,NULL,5,'≥100% (OK)',2);
INSERT INTO "ScoringDomain"("id","versionId","code","name","weight","orderIndex") VALUES ('dom_D2','ver_1','D2','Qualité intrinsèque du projet',0.18,1);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C1','dom_D2','D2C1','Foncier & autorisations','QUAL'::"CriterionType",0.2,'land_permits_status',true,0,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C1_absentes','crit_D2C1','absentes','Titre non purgé / autorisations absentes',0,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C1_partielles','crit_D2C1','partielles','Partielles',3,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C1_definitives','crit_D2C1','definitives','Titre purgé + autorisations définitives',5,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C2','dom_D2','D2C2','Marché & positionnement','QUAL'::"CriterionType",0.2,'market_positioning',false,NULL,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C2_sur_positionne','crit_D2C2','sur_positionne','Sur-positionné / sur-offre',1,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C2_moyen','crit_D2C2','moyen','Correct',3,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C2_aligne','crit_D2C2','aligne','Aligné / forte demande',5,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C3','dom_D2','D2C3','Complexité technique','QUAL'::"CriterionType",0.15,'technical_complexity',false,NULL,2);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C3_elevee','crit_D2C3','elevee','Élevée',1,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C3_moyenne','crit_D2C3','moyenne','Moyenne',3,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C3_standard','crit_D2C3','standard','Standard',5,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C4','dom_D2','D2C4','Avancement vs planning','NUM'::"CriterionType",0.15,'progress_vs_plan',false,NULL,3);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D2C4_0','crit_D2C4',NULL,80,0,'<80% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D2C4_1','crit_D2C4',80,100,3,'80-100% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D2C4_2','crit_D2C4',100,NULL,5,'≥100% (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C5','dom_D2','D2C5','Litiges clients / SAV','QUAL'::"CriterionType",0.1,'sav_litigation',false,NULL,4);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C5_eleve','crit_D2C5','eleve','Élevé',1,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C5_moyen','crit_D2C5','moyen','Moyen',3,1);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C5_faible','crit_D2C5','faible','Faible',5,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C6','dom_D2','D2C6','Sensibilité macro / subvention','QUAL'::"CriterionType",0.1,'macro_sensitivity',false,NULL,5);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C6_elevee','crit_D2C6','elevee','Élevée',1,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D2C6_faible','crit_D2C6','faible','Faible',5,1);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D2C7','dom_D2','D2C7','Coût foncier / CA','NUM'::"CriterionType",0.1,'land_cost_ratio',false,NULL,6);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D2C7_0','crit_D2C7',NULL,25,5,'≤25% (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D2C7_1','crit_D2C7',25,35,3,'25-35% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D2C7_2','crit_D2C7',35,NULL,0,'>35% (critique)',2);
INSERT INTO "ScoringDomain"("id","versionId","code","name","weight","orderIndex") VALUES ('dom_D3','ver_1','D3','Commercial & Cash-flow',0.28,2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C1','dom_D3','D3C1','Préventes sécurisées (encaissées / CA)','NUM'::"CriterionType",0.25,'pre_sale_rate',false,NULL,0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C1_0','crit_D3C1',NULL,25,0,'<25% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C1_1','crit_D3C1',25,40,3,'25-40% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C1_2','crit_D3C1',40,NULL,5,'≥40% (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C2','dom_D3','D3C2','Ventes vs planning','NUM'::"CriterionType",0.1,'sales_vs_plan',false,NULL,1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C2_0','crit_D3C2',NULL,80,0,'<80% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C2_1','crit_D3C2',80,100,3,'80-100% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C2_2','crit_D3C2',100,NULL,5,'≥100% (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C3','dom_D3','D3C3','DSO (jours)','NUM'::"CriterionType",0.1,'dso_days',false,NULL,2);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C3_0','crit_D3C3',NULL,120,5,'≤120j (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C3_1','crit_D3C3',120,240,3,'120-240j (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C3_2','crit_D3C3',240,NULL,0,'>240j (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C4','dom_D3','D3C4','Cash coverage (cash / échéances)','NUM'::"CriterionType",0.2,'cash_coverage',false,NULL,3);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C4_0','crit_D3C4',NULL,1,0,'<1,0x (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C4_1','crit_D3C4',1,1.2,3,'1,0-1,2x (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C4_2','crit_D3C4',1.2,NULL,5,'≥1,2x (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C5','dom_D3','D3C5','Impasse brute','NUM'::"CriterionType",0.15,'funding_gap_pct',false,NULL,4);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C5_0','crit_D3C5',NULL,0.01,5,'≤0% (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C5_1','crit_D3C5',0.01,10,3,'0-10% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C5_2','crit_D3C5',10,NULL,0,'>10% (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C6','dom_D3','D3C6','Rotation stock (mois)','NUM'::"CriterionType",0.1,'stock_rotation_months',false,NULL,5);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C6_0','crit_D3C6',NULL,18,5,'≤18m (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C6_1','crit_D3C6',18,30,3,'18-30m (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C6_2','crit_D3C6',30,NULL,0,'>30m (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D3C7','dom_D3','D3C7','Marge brute stressée (prix -10%)','NUM'::"CriterionType",0.1,'stressed_margin_pct',false,NULL,6);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C7_0','crit_D3C7',NULL,10,0,'<10% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C7_1','crit_D3C7',10,15,3,'10-15% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D3C7_2','crit_D3C7',15,NULL,5,'≥15% (OK)',2);
INSERT INTO "ScoringDomain"("id","versionId","code","name","weight","orderIndex") VALUES ('dom_D4','ver_1','D4','Structuration financière & LGD',0.22,3);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D4C1','dom_D4','D4C1','Marge brute (CA - coûts directs)/CA','NUM'::"CriterionType",0.2,'gross_margin_pct',false,NULL,0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C1_0','crit_D4C1',NULL,15,0,'<15% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C1_1','crit_D4C1',15,25,3,'15-25% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C1_2','crit_D4C1',25,NULL,5,'≥25% (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D4C2','dom_D4','D4C2','LTC (dette / coût total)','NUM'::"CriterionType",0.15,'ltc',false,NULL,1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C2_0','crit_D4C2',NULL,60,5,'≤60% (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C2_1','crit_D4C2',60,80,3,'60-80% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C2_2','crit_D4C2',80,NULL,0,'>80% (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D4C3','dom_D4','D4C3','LTV stressée (dette / valeur×0,90)','NUM'::"CriterionType",0.2,'ltv_stressed',false,NULL,2);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C3_0','crit_D4C3',NULL,70,5,'≤70% (OK)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C3_1','crit_D4C3',70,85,3,'70-85% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C3_2','crit_D4C3',85,NULL,0,'>85% (critique)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D4C4','dom_D4','D4C4','Couverture garanties réalisable','NUM'::"CriterionType",0.2,'guarantee_coverage',false,NULL,3);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C4_0','crit_D4C4',NULL,90,0,'<90% (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C4_1','crit_D4C4',90,120,3,'90-120% (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C4_2','crit_D4C4',120,NULL,5,'≥120% (OK)',2);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D4C5','dom_D4','D4C5','Rang bancaire 1er rang','QUAL'::"CriterionType",0.1,'first_rank',false,NULL,4);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D4C5_non','crit_D4C5','non','Non 1er rang',0,0);
INSERT INTO "ScoringOption"("id","criterionId","value","label","score","orderIndex") VALUES ('opt_D4C5_oui','crit_D4C5','oui','1er rang',5,1);
INSERT INTO "ScoringCriterion"("id","domainId","code","name","type","weight","inputKey","isGate","gateThreshold","orderIndex") VALUES ('crit_D4C6','dom_D4','D4C6','Interest coverage (EBITDA / charges fin.)','NUM'::"CriterionType",0.15,'interest_coverage',false,NULL,5);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C6_0','crit_D4C6',NULL,1.5,0,'<1,5x (critique)',0);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C6_1','crit_D4C6',1.5,3,3,'1,5-3x (vigilance)',1);
INSERT INTO "ScoringRange"("id","criterionId","minIncl","maxExcl","score","label","orderIndex") VALUES ('rng_D4C6_2','crit_D4C6',3,NULL,5,'≥3x (OK)',2);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_RETARD_6M','ver_1','RF_RETARD_6M','Retard chantier ≥ 6 mois','{"clause":{"key":"construction_delay_months","op":"gte","value":6}}'::jsonb,'HIGH'::"Severity",ARRAY['D2','D5']::text[],15,true);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_CASH_LT_ECH','ver_1','RF_CASH_LT_ECH','Cash coverage < 1,0x','{"clause":{"key":"cash_coverage","op":"lt","value":1}}'::jsonb,'HIGH'::"Severity",ARRAY['D3','D5']::text[],25,true);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_IMPASSE_PERSIST','ver_1','RF_IMPASSE_PERSIST','Impasse de trésorerie persistante','{"clause":{"key":"funding_gap_persistent","op":"isTrue"}}'::jsonb,'HIGH'::"Severity",ARRAY['D3','D5']::text[],20,true);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_RESTRUCT','ver_1','RF_RESTRUCT','Première restructuration','{"clause":{"key":"restructured","op":"eq","value":"yes"}}'::jsonb,'MEDIUM'::"Severity",ARRAY['D5']::text[],25,false);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_FP_NEG','ver_1','RF_FP_NEG','Fonds propres négatifs','{"clause":{"key":"equity_negative","op":"isTrue"}}'::jsonb,'HIGH'::"Severity",ARRAY['D4','D5']::text[],25,false);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_NON_1ER_RANG','ver_1','RF_NON_1ER_RANG','Garantie non 1er rang','{"clause":{"key":"first_rank","op":"eq","value":"non"}}'::jsonb,'MEDIUM'::"Severity",ARRAY['D4','D5']::text[],25,true);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_IMPAYE_90J','ver_1','RF_IMPAYE_90J','Impayé ≥ 90 jours (souffrance automatique)','{"clause":{"key":"dpd_days","op":"gte","value":90}}'::jsonb,'BLOCKING'::"Severity",ARRAY['D5']::text[],0,false);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_PROJET_ARRET_12M','ver_1','RF_PROJET_ARRET_12M','Projet à l''arrêt ≥ 12 mois (souffrance automatique)','{"clause":{"key":"project_stopped_months","op":"gte","value":12}}'::jsonb,'BLOCKING'::"Severity",ARRAY['D5']::text[],0,false);
INSERT INTO "RedFlagRule"("id","versionId","code","name","rule","severity","impactDomains","malus","mitigable") VALUES ('rf_RF_LITIGE','ver_1','RF_LITIGE','Action en justice / contentieux (CTX)','{"clause":{"key":"legal_exposure","op":"eq","value":"litigation"}}'::jsonb,'BLOCKING'::"Severity",ARRAY['D5']::text[],0,false);
INSERT INTO "RegulatoryRegime"("id","code","name","effectiveFrom","active","hypEvaluationThreshold","restructuringPolicy") VALUES ('reg_BKAM_19G_2002','BKAM_19G_2002','Circulaire 19/G/2002 — Classification des créances','2002-12-23'::timestamp,false,1000000,'BKAM_19G');
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_19G_2002_SAIN','reg_BKAM_19G_2002','SAIN'::"RegulatoryClassCode",'Créance saine',0,false,false,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_19G_2002_SAIN','reg_BKAM_19G_2002','reg_BKAM_19G_2002_SAIN',0,'2002-12-23'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_19G_2002_PRE_DOUTEUX','reg_BKAM_19G_2002','PRE_DOUTEUX'::"RegulatoryClassCode",'Pré-douteuse',2,false,true,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_19G_2002_PRE_DOUTEUX','reg_BKAM_19G_2002','reg_BKAM_19G_2002_PRE_DOUTEUX',0.2,'2002-12-23'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_19G_2002_DOUTEUX','reg_BKAM_19G_2002','DOUTEUX'::"RegulatoryClassCode",'Douteuse',3,false,true,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_19G_2002_DOUTEUX','reg_BKAM_19G_2002','reg_BKAM_19G_2002_DOUTEUX',0.5,'2002-12-23'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_19G_2002_COMPROMIS','reg_BKAM_19G_2002','COMPROMIS'::"RegulatoryClassCode",'Compromise',4,false,true,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_19G_2002_COMPROMIS','reg_BKAM_19G_2002','reg_BKAM_19G_2002_COMPROMIS',1,'2002-12-23'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_19G_2002_CTX','reg_BKAM_19G_2002','CTX'::"RegulatoryClassCode",'Contentieux',5,false,true,true);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_19G_2002_CTX','reg_BKAM_19G_2002','reg_BKAM_19G_2002_CTX',1,'2002-12-23'::timestamp);
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_19G_2002_trg_0','reg_BKAM_19G_2002','reg_BKAM_19G_2002_PRE_DOUTEUX','DPD'::"TriggerKind",90,179,NULL,10,'Impayé 90j (art.5)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_19G_2002_trg_1','reg_BKAM_19G_2002','reg_BKAM_19G_2002_DOUTEUX','DPD'::"TriggerKind",180,359,NULL,20,'Impayé 180j (art.6)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_19G_2002_trg_2','reg_BKAM_19G_2002','reg_BKAM_19G_2002_COMPROMIS','DPD'::"TriggerKind",360,NULL,NULL,30,'Impayé 360j (art.7)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_19G_2002_trg_3','reg_BKAM_19G_2002','reg_BKAM_19G_2002_PRE_DOUTEUX','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"financials_unavailable","op":"isTrue"}}'::jsonb,8,'Situation financière non évaluable (art.5.4)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_19G_2002_trg_4','reg_BKAM_19G_2002','reg_BKAM_19G_2002_DOUTEUX','LEGAL'::"TriggerKind",NULL,NULL,'{"clause":{"key":"judicial_recovery","op":"isTrue"}}'::jsonb,25,'Redressement judiciaire (art.6.5)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_19G_2002_trg_5','reg_BKAM_19G_2002','reg_BKAM_19G_2002_CTX','LEGAL'::"TriggerKind",NULL,NULL,'{"clause":{"key":"legal_exposure","op":"eq","value":"litigation"}}'::jsonb,40,'Action en justice / contestation (art.7.5)');
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_DEPOT_GARANTIE','reg_BKAM_19G_2002','DEPOT_GARANTIE','Dépôt de garantie (deposit)',true,1,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_GARANTIE_ETAT','reg_BKAM_19G_2002','GARANTIE_ETAT','Garantie État / CCG homologuée',true,1,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_NANTISSEMENT_DAT','reg_BKAM_19G_2002','NANTISSEMENT_DAT','Nantissement DAT / bons de caisse de l''établissement',true,1,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_GARANTIE_BANCAIRE','reg_BKAM_19G_2002','GARANTIE_BANCAIRE','Garantie banque 1er ordre / assurance-crédit',true,0.8,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_NANTISSEMENT_TITRES','reg_BKAM_19G_2002','NANTISSEMENT_TITRES','Nantissement titres (autres établissements)',true,0.8,0,'TITRES',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_HYP_RANG1','reg_BKAM_19G_2002','HYP_RANG1','Hypothèque immobilière 1er rang',true,0.5,0,'HYPOTHECAIRE',true);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_HYP_RANG_INF','reg_BKAM_19G_2002','HYP_RANG_INF','Hypothèque de rang inférieur',true,0.5,0,'HYPOTHECAIRE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_ATTESTATION_MARCHE','reg_BKAM_19G_2002','ATTESTATION_MARCHE','Attestation de droits constatés (marchés publics)',true,0.5,0,'TITRES',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_NANTISSEMENT_VEHICULE','reg_BKAM_19G_2002','NANTISSEMENT_VEHICULE','Nantissement véhicules neufs',true,0.5,0,'VEHICULES',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_19G_2002_CAUTION_PERSO','reg_BKAM_19G_2002','CAUTION_PERSO','Caution personnelle (non admise en déduction)',false,0,1,'NONE',false);
INSERT INTO "RegulatoryRegime"("id","code","name","effectiveFrom","active","hypEvaluationThreshold","restructuringPolicy") VALUES ('reg_BKAM_1W_2025','BKAM_1W_2025','Circulaire 1/W/2025 — Classification & provisionnement','2027-01-01'::timestamp,true,5000000,'BKAM_1W');
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_1W_2025_SAIN','reg_BKAM_1W_2025','SAIN'::"RegulatoryClassCode",'Créance saine',0,false,false,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_1W_2025_SAIN','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SAIN',0,'2027-01-01'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_1W_2025_SENSIBLE','reg_BKAM_1W_2025','SENSIBLE'::"RegulatoryClassCode",'Créance sensible (surveillance)',1,true,false,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_1W_2025_SENSIBLE','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE',0.1,'2027-01-01'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_1W_2025_PRE_DOUTEUX','reg_BKAM_1W_2025','PRE_DOUTEUX'::"RegulatoryClassCode",'Pré-douteuse',2,false,true,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_1W_2025_PRE_DOUTEUX','reg_BKAM_1W_2025','reg_BKAM_1W_2025_PRE_DOUTEUX',0.2,'2027-01-01'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_1W_2025_DOUTEUX','reg_BKAM_1W_2025','DOUTEUX'::"RegulatoryClassCode",'Douteuse',3,false,true,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_1W_2025_DOUTEUX','reg_BKAM_1W_2025','reg_BKAM_1W_2025_DOUTEUX',0.5,'2027-01-01'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_1W_2025_COMPROMIS','reg_BKAM_1W_2025','COMPROMIS'::"RegulatoryClassCode",'Compromise',4,false,true,false);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_1W_2025_COMPROMIS','reg_BKAM_1W_2025','reg_BKAM_1W_2025_COMPROMIS',1,'2027-01-01'::timestamp);
INSERT INTO "RegulatoryClass"("id","regimeId","code","label","orderIndex","isWatchList","isDefault","blocksGo") VALUES ('reg_BKAM_1W_2025_CTX','reg_BKAM_1W_2025','CTX'::"RegulatoryClassCode",'Contentieux',5,false,true,true);
INSERT INTO "ProvisionRate"("id","regimeId","classId","rate","effectiveFrom") VALUES ('pr_reg_BKAM_1W_2025_CTX','reg_BKAM_1W_2025','reg_BKAM_1W_2025_CTX',1,'2027-01-01'::timestamp);
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_0','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"seizure_notice","op":"isTrue"}}'::jsonb,4,'Saisie-arrêt / ATD (art.5.1)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_1','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"financials_late_7m","op":"isTrue"}}'::jsonb,4,'États comptables non reçus 7 mois après clôture (art.5.2)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_2','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"negative_credit_bureau","op":"isTrue"}}'::jsonb,4,'Information négative Crédit Bureau / SCIP (art.5.2)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_3','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"commercialization_below_50_1y","op":"isTrue"}}'::jsonb,6,'Commercialisation < 50% un an après travaux (art.5.3)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_4','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"admin_problems_over_1y","op":"isTrue"}}'::jsonb,6,'Problèmes administratifs > 1 an (art.5.3)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_5','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"construction_delay_over_1y","op":"isTrue"}}'::jsonb,6,'Retard construction > 1 an vs planning (art.5.3)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_6','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"bp_significant_gap","op":"isTrue"}}'::jsonb,6,'Décalage significatif vs business plan (art.5.3)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_7','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"all":[{"key":"revenue_drop_pct","op":"gte","value":50}]}'::jsonb,5,'Baisse du CA ≥ 50% en un an (art.5.5)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_8','reg_BKAM_1W_2025','reg_BKAM_1W_2025_SENSIBLE','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"debt_equity_ratio","op":"gt","value":3}}'::jsonb,5,'Dettes fin./FP > 3 (art.5.5)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_9','reg_BKAM_1W_2025','reg_BKAM_1W_2025_PRE_DOUTEUX','DPD'::"TriggerKind",90,179,NULL,10,'Impayé > 90j (art.10)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_10','reg_BKAM_1W_2025','reg_BKAM_1W_2025_DOUTEUX','DPD'::"TriggerKind",180,359,NULL,20,'Impayé > 180j (art.11)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_11','reg_BKAM_1W_2025','reg_BKAM_1W_2025_COMPROMIS','DPD'::"TriggerKind",360,NULL,NULL,30,'Impayé > 360j (art.12)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_12','reg_BKAM_1W_2025','reg_BKAM_1W_2025_PRE_DOUTEUX','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"financials_unavailable","op":"isTrue"}}'::jsonb,8,'Situation financière non évaluable (art.10.6)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_13','reg_BKAM_1W_2025','reg_BKAM_1W_2025_DOUTEUX','LEGAL'::"TriggerKind",NULL,NULL,'{"clause":{"key":"judicial_recovery","op":"isTrue"}}'::jsonb,22,'Redressement judiciaire (art.11.6)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_14','reg_BKAM_1W_2025','reg_BKAM_1W_2025_COMPROMIS','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"finished_2y_no_sales","op":"isTrue"}}'::jsonb,28,'Projet finalisé ≥ 2 ans, commercialisation figée (art.12.6)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_15','reg_BKAM_1W_2025','reg_BKAM_1W_2025_COMPROMIS','QUALITATIVE'::"TriggerKind",NULL,NULL,'{"clause":{"key":"project_stopped_over_1y","op":"isTrue"}}'::jsonb,28,'Projet à l''arrêt > 1 an (art.12.7)');
INSERT INTO "RegulatoryTrigger"("id","regimeId","classId","kind","dpdMin","dpdMax","condition","priority","description") VALUES ('reg_BKAM_1W_2025_trg_16','reg_BKAM_1W_2025','reg_BKAM_1W_2025_CTX','LEGAL'::"TriggerKind",NULL,NULL,'{"clause":{"key":"legal_exposure","op":"eq","value":"litigation"}}'::jsonb,40,'Action en justice / contestation (art.12.8)');
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_DEPOT_GARANTIE','reg_BKAM_1W_2025','DEPOT_GARANTIE','Dépôt de garantie (deposit)',true,1,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_GARANTIE_ETAT','reg_BKAM_1W_2025','GARANTIE_ETAT','Garantie État / SNGFE homologuée',true,1,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_NANTISSEMENT_DAT','reg_BKAM_1W_2025','NANTISSEMENT_DAT','Nantissement DAT / bons de caisse de l''établissement',true,1,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_GARANTIE_BANCAIRE','reg_BKAM_1W_2025','GARANTIE_BANCAIRE','Garantie banque 1er ordre / assurance-crédit',true,0.8,0,'NONE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_NANTISSEMENT_TITRES','reg_BKAM_1W_2025','NANTISSEMENT_TITRES','Nantissement titres (autres établissements)',true,0.8,0,'TITRES',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_HYP_RANG1','reg_BKAM_1W_2025','HYP_RANG1','Hypothèque immobilière 1er rang',true,0.5,0,'HYPOTHECAIRE',true);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_HYP_RANG_INF','reg_BKAM_1W_2025','HYP_RANG_INF','Hypothèque de rang inférieur',true,0.5,0,'HYPOTHECAIRE',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_ATTESTATION_MARCHE','reg_BKAM_1W_2025','ATTESTATION_MARCHE','Attestation de droits constatés (marchés publics)',true,0.5,0,'TITRES',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_NANTISSEMENT_VEHICULE','reg_BKAM_1W_2025','NANTISSEMENT_VEHICULE','Nantissement véhicules neufs',true,0.5,0,'VEHICULES',false);
INSERT INTO "GuaranteeType"("id","regimeId","code","label","eligible","quotity","haircut","abatementProfile","requiresRank1") VALUES ('reg_BKAM_1W_2025_CAUTION_PERSO','reg_BKAM_1W_2025','CAUTION_PERSO','Caution personnelle (non admise en déduction)',false,0,1,'NONE',false);
INSERT INTO "Promoter"("id","name","legalForm","groupName","yearsExperience","completedProjects","internalRating","updatedAt") VALUES ('promo_1','Atlas Développement SA','SA','Groupe Atlas',15,8,'BBB',now());
INSERT INTO "Promoter"("id","name","legalForm","yearsExperience","completedProjects","internalRating","updatedAt") VALUES ('promo_2','Nouvelle Résidence SARL','SARL',3,1,'B',now());
INSERT INTO "RealEstateProject"("id","reference","name","promoterId","rmId","city","region","projectType","segment","zone","groupId","totalUnits","landAreaSqm","builtAreaSqm","totalCost","loanAmount","ownEquity","status","updatedAt") VALUES ('proj_1','PI-2026-001','Résidence Les Jardins de l''Atlas','promo_1','user_RELATIONSHIP_MANAGER','Casablanca','Casablanca-Settat','Résidentiel haut standing','moyen_haut','casa_centre','GRP_ATLAS',120,8000,14000,180000000,110000000,70000000,'EN_ANALYSE',now());
INSERT INTO "RealEstateProject"("id","reference","name","promoterId","rmId","city","region","projectType","segment","zone","totalUnits","landAreaSqm","builtAreaSqm","totalCost","loanAmount","ownEquity","status","updatedAt") VALUES ('proj_2','PI-2026-002','Résidence Annour','promo_2','user_RELATIONSHIP_MANAGER','Marrakech','Marrakech-Safi','Résidentiel social','intermediaire','marrakech',60,3000,4500,45000000,38000000,7000000,'EN_ANALYSE',now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_0','proj_1','promoter_completed_projects',8,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_1','proj_1','promoter_gearing',85,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_2','proj_1','governance_quality',NULL,'claire',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_3','proj_1','mono_project_concentration',35,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_4','proj_1','promoter_type',NULL,'structure',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_5','proj_1','equity_injected_ratio',100,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_6','proj_1','land_permits_status',NULL,'definitives',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_7','proj_1','market_positioning',NULL,'aligne',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_8','proj_1','technical_complexity',NULL,'standard',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_9','proj_1','progress_vs_plan',100,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_10','proj_1','sav_litigation',NULL,'faible',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_11','proj_1','macro_sensitivity',NULL,'faible',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_12','proj_1','land_cost_ratio',22,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_13','proj_1','pre_sale_rate',62,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_14','proj_1','sales_vs_plan',100,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_15','proj_1','dso_days',90,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_16','proj_1','cash_coverage',1.35,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_17','proj_1','funding_gap_pct',0,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_18','proj_1','stock_rotation_months',16,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_19','proj_1','stressed_margin_pct',18,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_20','proj_1','gross_margin_pct',27,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_21','proj_1','ltc',61,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_22','proj_1','ltv_stressed',65,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_23','proj_1','guarantee_coverage',125,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_24','proj_1','first_rank',NULL,'oui',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_25','proj_1','interest_coverage',3.2,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_26','proj_1','dpd_days',0,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_27','proj_1','construction_delay_months',0,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_28','proj_1','project_stopped_months',0,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_29','proj_1','restructured',NULL,'no',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_1_in_30','proj_1','legal_exposure',NULL,'clear',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_0','proj_2','promoter_completed_projects',1,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_1','proj_2','promoter_gearing',160,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_2','proj_2','governance_quality',NULL,'partielle',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_3','proj_2','mono_project_concentration',70,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_4','proj_2','promoter_type',NULL,'opportuniste',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_5','proj_2','equity_injected_ratio',70,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_6','proj_2','land_permits_status',NULL,'partielles',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_7','proj_2','market_positioning',NULL,'moyen',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_8','proj_2','technical_complexity',NULL,'moyenne',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_9','proj_2','progress_vs_plan',75,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_10','proj_2','sav_litigation',NULL,'moyen',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_11','proj_2','macro_sensitivity',NULL,'elevee',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_12','proj_2','land_cost_ratio',32,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_13','proj_2','pre_sale_rate',18,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_14','proj_2','sales_vs_plan',70,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_15','proj_2','dso_days',260,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_16','proj_2','cash_coverage',0.85,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_17','proj_2','funding_gap_pct',15,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_18','proj_2','stock_rotation_months',32,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_19','proj_2','stressed_margin_pct',9,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_20','proj_2','gross_margin_pct',13,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_21','proj_2','ltc',84,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_22','proj_2','ltv_stressed',88,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_23','proj_2','guarantee_coverage',60,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_24','proj_2','first_rank',NULL,'non',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_25','proj_2','interest_coverage',1.2,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_26','proj_2','dpd_days',110,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_27','proj_2','construction_delay_months',8,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_28','proj_2','project_stopped_months',0,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_29','proj_2','restructured',NULL,'yes',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_30','proj_2','restructuring_count',1,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_31','proj_2','restructuring_deferral_months',12,NULL,NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_32','proj_2','legal_exposure',NULL,'watch',NULL,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_33','proj_2','funding_gap_persistent',NULL,NULL,true,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_34','proj_2','commercialization_below_50_1y',NULL,NULL,true,now());
INSERT INTO "ProjectInput"("id","projectId","key","valueNum","valueStr","valueBool","updatedAt") VALUES ('proj_2_in_35','proj_2','construction_delay_over_1y',NULL,NULL,false,now());
INSERT INTO "Guarantee"("id","projectId","typeId","description","marketValue","rank","recentlyEvaluated") VALUES ('gar_1','proj_1','reg_BKAM_19G_2002_HYP_RANG1','Hypothèque 1er rang sur le foncier',120000000,1,true);
INSERT INTO "Guarantee"("id","projectId","typeId","description","marketValue","rank","recentlyEvaluated") VALUES ('gar_2','proj_1','reg_BKAM_19G_2002_GARANTIE_BANCAIRE','Garantie bancaire de premier ordre',20000000,1,true);
INSERT INTO "Guarantee"("id","projectId","typeId","description","marketValue","rank","recentlyEvaluated") VALUES ('gar_3','proj_2','reg_BKAM_19G_2002_HYP_RANG1','Hypothèque foncier',28000000,2,true);
